# Generated by Django 3.0.4 on 2020-05-19 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20200519_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default='Default', on_delete=django.db.models.deletion.SET_DEFAULT, to='blog.Category'),
        ),
    ]
